name: Kiem tra Toan hoc
on: [push]

jobs:
  math-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Phep tinh dung (Se pass)
        run: python -c "print(10 + 5)"

      - name: Phep tinh sai (Se fail)
        # Lệnh này sẽ báo lỗi vì chia cho 0
        run: python -c "print(10 / 0)"
        
      - name: Buoc nay se khong chay
        run: echo "Toi se khong bao gio duoc in ra vi buoc tren da chet!"