name: Test Node.js App
on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Lay code ve
        uses: actions/checkout@v3

      - name: Cai dat Node.js phien ban 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Kiem tra phien ban Node
        run: node -v
        
      - name: Chay thu ung dung
        run: node app.js